Kirill shop mvvm
yur4kur/UiLuxury_TeamProject pull request #45
Opened 2024-04-05 09:09 UTC by Kirill-iOSwift

2024-04-05 11:02 UTC, eldarovsky approved these changes
Можно подумать о том, чтобы счет не уезжал за экран.

2024-04-05 11:02 UTC, eldarovsky commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewController.swift
> +        static let ups = "Нехватает денег"
Исправить на "Не хватает"

2024-04-05 11:02 UTC, eldarovsky commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewController.swift
> +        static let messege = "Твой балаланс ниже стоимости покупки"
Исправить на message и "счет"

2024-04-05 11:02 UTC, eldarovsky commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewController.swift
>      // MARK: View Model
Добавить пустую строку после марки. Проверить, чтобы у остальных марок была пустая строка до и после.

2024-04-05 11:02 UTC, eldarovsky commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewController.swift
>      ///Количество секций
Удалить документацию у стандартных методов UITableViewDataSource и UITableViewDelegate.

2024-04-05 11:02 UTC, eldarovsky commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewController.swift
> +        title = viewModel.walletCount
**title = viewModel.walletCount перенести во viewDidAppear:**

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        title = viewModel.walletCount
    }

2024-04-05 11:02 UTC, eldarovsky commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewModel.swift
>      /// Инициализация данных пользователя из стартовой вью-модели
Перенести над методами.

2024-04-06 05:20 UTC, yur4kur requested changes
Модель - отлично получилась, я считаю. После доработок - конфетка будет))

2024-04-06 05:20 UTC, yur4kur commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewController.swift
>      //TODO: Добавить алерт
Удалить TODO, если уже выполнена

2024-04-06 05:20 UTC, yur4kur commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewController.swift
> +        static let messege = "Твой балаланс ниже стоимости покупки"
Насчет message согласен, а про "счет" не понял. Это ведь сообщение Алерта, оно вроде в тему здесь.

2024-04-06 05:20 UTC, yur4kur commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewModel.swift
> +    var shopItems: [Item] { get }
Поля в протоколе надо задокументировать. Эта же документация будет подтягиваться к ним во всех объектах, которые подпишутся под этот протокол.

2024-04-06 05:20 UTC, yur4kur commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewModel.swift
> +    func cellConfig(cell: UITableViewCell, indexPath: IndexPath, text: String) {
Вот этот метод мне особенно понравился. Его можно доработать и вынести в глобальный, чтобы можно было применять в обеих таблицах на разных контроллерах.

2024-04-06 05:20 UTC, yur4kur commented on UiLuxury_TeamProject/Services/DataSource.swift
> +        "Дополнительное очко \nза каждое нажатие кнопки",
Если откажемся от галочки и реализуем покупку через Алерт, то эти изменения будут не нужны. Поставь сюда TODO: "Удалить \n, если покупка будет через Алерт"

2024-04-06 05:20 UTC, yur4kur commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewModel.swift
> +    func buy(indexPath: IndexPath, complition: () -> Void, alertComplition: () -> Void)
Должно быть completion и alertCompletion

2024-04-06 05:24 UTC, eldarovsky commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewController.swift
> +        static let messege = "Твой балаланс ниже стоимости покупки"
На первом экране title был "счет", на моем экране под изображением "счет". Чтобы сделать в одном стиле, решил, что счет будет логичнее баланса.

2024-04-06 07:42 UTC, Kirill-iOSwift commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewController.swift
> +        static let ups = "Нехватает денег"
Исправил

2024-04-06 07:46 UTC, Kirill-iOSwift commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewController.swift
> +        static let messege = "Твой балаланс ниже стоимости покупки"
Исправил

2024-04-06 07:58 UTC, Kirill-iOSwift commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewController.swift
>      ///Количество секций
👌🏻

2024-04-06 08:06 UTC, Kirill-iOSwift commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewController.swift
>      // MARK: View Model
Добавил

2024-04-06 08:11 UTC, Kirill-iOSwift commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewController.swift
> +        title = viewModel.walletCount
Перенес

2024-04-06 08:13 UTC, Kirill-iOSwift commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewModel.swift
>      /// Инициализация данных пользователя из стартовой вью-модели
Перенес

2024-04-06 08:15 UTC, Kirill-iOSwift commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewController.swift
>      //TODO: Добавить алерт
Удалил

2024-04-06 08:15 UTC, Kirill-iOSwift commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewModel.swift
> +    var shopItems: [Item] { get }
Оформил

2024-04-06 08:16 UTC, Kirill-iOSwift commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewModel.swift
> +    func cellConfig(cell: UITableViewCell, indexPath: IndexPath, text: String) {
👍🏻

2024-04-06 08:17 UTC, Kirill-iOSwift commented on UiLuxury_TeamProject/Services/DataSource.swift
> +        "Дополнительное очко \nза каждое нажатие кнопки",
Добавил

2024-04-06 08:19 UTC, Kirill-iOSwift commented on UiLuxury_TeamProject/Scenes/ShopScene/ShopViewModel.swift
> +    func buy(indexPath: IndexPath, complition: () -> Void, alertComplition: () -> Void)
Исправил

2024-04-06 08:49 UTC, merged